config/routes.rb
Rails.application.routes.draw do
  get "login" => "sessions#new"

    get "logout" => "sessions#destroy"

  get "dashboard" => "dashboard#static"

  get "about_us" => "welcome#about"

  resources :sessions, only: [:create]

resources :users, only: [:new, :create]
  root 'welcome#index'

  get "home" => "welcome/index"

  get "Contact" => "welcome#contact"

  get 'users/new'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
 has_secure_password

 def email=(value)
 	#this is for eventhough if we type our email in caps but it will take it as small
 	value = value.strip.downcase
 	write_attribute :email, value
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  private

  def sign_in(user)
   
   session[:user_id] = user.id if user.present?

  end
  def sign_out
   
   session[:user_id] = nil

  end


def current_user

  User.find_by id: session[:user_id] if session[:user_id]

end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def static
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new


  end

  def create

   user=User.find_by email: params[:email].downcase

   if user && user.authenticate(params[:password])
   	#sign in
   	session[:user_id] = user.id

   	flash[:notice] = "you are signed in"

   	redirect_to root_url
   else
   flash.now[:alert] = "Invalid email/password"

   render 'new'
  end

  end 
  
  def destroy

  	sign_out
    
    #session[:user_id] = nil
    flash[:notice] = "you are signed out"

    redirect_to root_url


  end
  


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end
  def create
  	@user=User.new(user_params)

  	if @user.save
  		flash[:notice] = "you are a new user"
      session[:user_id] = @user.id
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end

  	private

  	def user_params

  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  @users=User.all

  end
  def about
  end

  def contact
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/static.html.erb
<!-- Container (Pricing Section) -->
<p style="page-break-after: always;">&nbsp;</p>
<p style="page-break-before: always;">&nbsp;</p>

<div class="container-fluid">
  <div class="text-center">
    <h2> MINING PACK PRICING </h2>
    <h4>Choose a payment plan that works for you</h4>
  </div>

<p style="page-break-after: always;">&nbsp;</p>
<p style="page-break-after: always;">&nbsp;</p>

  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-default text-center">
        <div class="panel-heading">
          <h2>Pick Axe</h2>
          <h2> Silver </h2>
        </div>
        <div class="panel-body">
        	<h2>$30</h2>
        </div>
        <div class="panel-footer">
          <p><strong>163 GH/s</strong> Hash Power</p>
          <p><strong></strong> Life time Mining</p>
          <p><strong></strong> Electricity fee</p>
          
      </div>
      <div>
          <button class="btn btn-lg">SELECT</button>
        </div>
      </div> 
    </div>
   <div class="col-sm-4">
      <div class="panel panel-default text-center">
        <div class="panel-heading">
          <h2>Pick Axe</h2>
          <h2> Gold </h2>
        </div>
        <div class="panel-body">
        	<h2>$300</h2>
        </div>
        <div class="panel-footer">
          <p><strong>1.63 TH/s</strong> Hash Power</p>
          <p><strong></strong> Life time Mining</p>
          <p><strong></strong> Electricity fee</p>
          
      </div>
      <div>
          <button class="btn btn-lg">SELECT</button>
        </div>
      </div> 
    </div>
   <div class="col-sm-4">
      <div class="panel panel-default text-center">
        <div class="panel-heading">
          <h2>Pick Axe</h2>
          <h2> Platinum </h2>
        </div>
        <div class="panel-body">
        	<h2>$1000</h2>
        </div>
        <div class="panel-footer">
          <p><strong>5.433 TH/s</strong> Hash Power</p>
          <p><strong></strong> Life time Mining</p>
          <p><strong></strong> Electricity fee</p>
          
      </div>
      <div>
          <button class="btn btn-lg">SELECT</button>
        </div>
      </div> 
    </div> 
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Bitcoin india</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  <% if current_user.present? %>
welcome <%= current_user.email %> <%= link_to 'Logout',logout_path %>


<%else%>
    <nav class="navbar navbar-inverse">
      
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="brand" href="#">
            <!-- UNCOMMENT THE CSS VALUES TO TEST OTHER DIMENTIONS -->
            <img  <%=  link_to image_tag("bitcoinindia.png", alt: "logo"),
        '/' %> 
            </a></div>
            
      <a class="navbar-brand" href="#">Bitcoin India</a> 
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-top: 0px; opacity: 1; background-color: rgba(59, 59, 59, 0.74902);">
<div class="container">

<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="/">

<div id="main-img"></div>
</a>
<div class="btc-values">
<div class="navbar-header" style="margin-left: 20px;min-width:97%;">
<div>
<div style="float: left">
<span class="price_ticker" style="color: #fff">Buy 1 BTC= <span id="buyvalue"> 497703</span></span>
</div>
<div style="float: left;">
<select name="select" id="select_currency2" class="select" onchange="convertrates('buy', 'select_currency2');">
<option value="INR">INR</option>
<option value="USD">USD</option>
<option value="NZD">NZD</option>
<option value="TWD">TWD</option>
<option value="MYR">MYR</option>
<option value="AUD">AUD</option>
<option value="SGD">SGD</option>
<option value="EUR">EUR</option>
<option value="JPY">JPY</option>
<option value="GBP">GBP</option>
<option value="CAD">CAD</option>
<option value="CNY">CNY</option>
</select>
</div>
</div>
<div>
<div style="float: left">
<span class="price_ticker" style="color: #fff">Sell 1 BTC= <span id="sellvalue"> 494571</span></span>
</div>
<div style="float: left;">
<select name="select" id="select_currency3" class="select" onchange="convertrates('sell', 'select_currency3');">
<option value="INR">INR</option>
<option value="USD">USD</option>
<option value="NZD">NZD</option>
<option value="TWD">TWD</option>
<option value="MYR">MYR</option>
<option value="AUD">AUD</option>
<option value="SGD">SGD</option>
<option value="EUR">EUR</option>
<option value="JPY">JPY</option>
<option value="GBP">GBP</option>
<option value="CAD">CAD</option>
<option value="CNY">CNY</option>
</select>
</div>
</div>
</div>
</div>
</div>

<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav navbar-right">

<li><a href="#tbuy" style="padding-top: 15px;">BUY &amp; SELL</a></li>
<li class=""><a target="_blank" href="https://www.bitcoin-india.org/" style="padding-top: 15px;">EXCHANGE</a></li>
<li class=""><a target="_blank" href="https://www.bitcoin-india.org/coin_swap" style="padding-top: 15px;">COIN SWAP</a></li>
<li class="btn-group ">
<a class="dropdown-toggle" data-toggle="dropdown" href="https://pool.bitcoin-india.org/" style="padding-top: 15px;">
MINING
<span class="caret"></span>
</a>
<ul class="dropdown-menu">
<li class=""><a href="/mining">HOSTED MINING</a></li>
<li class=""><a href="/mining_pack_pricing">MINING PACK</a></li>
<li><a target="_blank" href="https://pool.bitcoin-india.org/">MINING POOL</a></li>
<li><a href="https://alloscomp.com/bitcoin/calculator" target="_blank" title="Bitcoin mining profit calculator">BITCOIN MINING PROFIT CALCULATOR</a></li>
</ul>
</li>
<li class=""><a href="https://www.bitcoin-india.org/club" style="padding-top: 15px;">CLUB</a></li>

<li><a href="#tjoin" style="padding-top: 15px;">LOGIN / JOIN</a></li>
</ul>
</div>
</div>

</nav>


<% end %>

  	<%= notice %>
  	<%= alert %>
    <%= yield %>
  </body>
</html>

app/views/layouts/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="#">Features</a>
      <a class="nav-item nav-link" href="#">Pricing</a>
      <a class="nav-item nav-link disabled" href="#">Disabled</a>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_for @user do |f|%>
<div class="text-center">
<div>
	<h3>
	<%= f.label :email%><br/>
	<%= f.text_field :email%>
   </h3>
</div>

<div>
	<h3>
	<%= f.label :password%><br/>
	<%= f.password_field :password%>
   </h3>
</div>

<div>
	<h3>
	<%= f.label :password_confirmation%><br/>
	<%= f.password_field :password_confirmation%>
    </h3>
</div>



	<h3><%= f.submit 'Signin'%></h3>
</div>

<% end %>

app/views/welcome/about.html.erb
<h1>About Bitcoin INDIA™ Company</h1>
<pre>Bitcoin India™ Software Services Pvt. Ltd. is a private company based in India that provides web and mobile digital wallet services. Our mission is to provide the easiest and most secure digital currency value-added services for consumers and merchants.

Bitcoin India™ plays a leading role in every segment of the Bitcoin ecosystem, offering a digital currency exchange (https://bitcoin-india.org/exchange), a mining pool, payment processing, consumer wallets, instant coin swap (coin exchange), and blockchain-related services.

Bitcoin India™ is the longest-running, one-and-only Indian exchange and wallet service provider that owns and operates Global “Mining Pool” (https://pool.bitcoin-india.org/). Bitcoin India™ truly believes in the new blockchain technology and strives to be the premier technical service provider to the world from India. We are working hard to secure the transactional network with Bitcoin Mining to support the "World of Bitcoin/Blockchain Ecosystem.” We are a proud supporter of Bitcoin Core Team.

==========

==========

More info:

Bitcoin India™ - exists at global locations, having three different locations at India which includes one of the country's most prestigious location:

T-hub (initiated by Telangana Govt),

IIIT<International Institute of Information Technology> Hyderabad Campus,

Gachibowli, Hyderabad,

Telangana, India - 500032

https://www.facebook.com/photo.php?fbid=1308254199233129&set=pcb.1308255249233024&type=3&theater

And, Bitcoin India™ having it's registered office at Andhra Pradesh, having one of the operations centre at Chennai, Bitcoin India™ does have it's data centres located at various global locations, to name few, India, Iceland, USA, Venezuela, China, Russia, Australia, and Malaysia., And, for security reasons the exact location details of our data centres are available for Bitcoin India™' mining user's wit KYC verification or to "Bitcoin India™ mining club" members only.

https://www.zaubacorp.com/company/BITCOIN-INDIA-SOFTWARE-SERVICES-PRIVATE-LIMITED/U74140AP2014PTC095552

==========

==========

“Bitcoin India™ wallet” App is ready!!!

Here is a link to download "Bitcoin India™ Wallet" from "Google Play store":

https://play.google.com/store/apps/details?id=com.bitcoinindia.Btci&hl=en

==========

</pre>

app/views/welcome/contact.html.erb
<h1> In contact page </h2>